## - Foi feito para fins de exemplo, mas é preferível não utilizar um ReplicaSet para subir containers e sim um Deployment

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias # deve ser igual lá embaixo
  template: # abaixo ficam as informações dos pods que serão gerenciados por esse replicaset
    metadata: # essas infos são iguais as definidas no arquivo portal-noticias.yaml
      name: portal-noticias
      labels:
        app: portal-noticias # deve ser igual lá em cima
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef: 
                name: portal-configmap

# - o interessante é que o serviço svc-portal-noticias continua redirecionando as chamadas para 
# cada pod de maneira transparente, funcionando como um loadbalancer