apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias # app foi escolhido arbitrariamente, bem como portal-noticias
spec:
  containers: # posso definir vários pares de (name, image), com o traço (-) sempre em name
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80 # o portal-noticias atende nesta porta
      envFrom: # importando as variáveis de ambiente do configmap especificado pelo name abaixo
        - configMapRef: 
            name: portal-configmap # vem do arquivo portal-configmap.yaml