apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  template: # abaixo fica informações do pod
    metadata:
      labels:
        app: sistema-noticias # deve ser igual lá embaixo
      name: sistema-noticias # nome de fato do pod
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
          volumeMounts: # os dois diretórios abaixo serão montados dentro do container
            - name: imagens # faz referência ao volume definido abaixo
              mountPath: /var/www/html/uploads
            - name: sessao
              mountPath: /tmp
      volumes:
        - name: imagens
          persistentVolumeClaim: 
            claimName: imagens-pvc # definido em imagens-pvc.yaml
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-pvc # definido em sessao-pvc.yaml
  selector:
    matchLabels:
      app: sistema-noticias # deve ser igual lá em cima
  serviceName: svc-sistema-noticias