apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-noticias-deployment
spec:
  #replicas: 1 # não é necessário, pois é 1 por default
  selector:
    matchLabels:
      app: sistema-noticias # deve ser igual lá embaixo
  template: # a partir daqui ficam as mesmas infos de um pod
    metadata:
      name: sistema-noticias # vai ser o nome do pod
      labels:
        app: sistema-noticias # deve ser igual lá em cima
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap # definido no arquivo sistema-configmap.yaml