apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  selector:
    app: sistema-noticias # o mesmo definido no arquivo sistema-noticias.yaml
  type: NodePort
  ports:
    - port: 80 # tudo que bater na porta 30001 (externo) ou 80 (interno), será redirecionado para a porta 80 do pod definido na label acima
      nodePort: 30001 # atende requisições do mundo externo nessa porta. Como estamos local, seria http://localhost:30001