apiVersion: v1
kind: PersistenceVolumeClaim
metadata:
  name: pvc-1
spec:
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    storageClassName: example # definido em metadata->name no arquivo sc.yaml