apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom: # importando as variáveis de ambiente do configmap especificado pelo name
        - configMapRef: 
            name: sistema-configmap # vem do arquivo sistema-configmap.yaml